project:
  type: website

website:
  title: "Safe & Robust RL for Power & Energy Systems"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial/index.qmd
        text: Tutorial
      - href: demos/index.qmd
        text: Demos
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: darkly   # Dark mode optimized
    css:
      - styles/hero.css
    toc: false