name: Publish Quarto Website

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
      - 'tutorials/**'
      - 'algorithms/**'
      - '**/*.md'
      - '**/*.qmd'
      - '.github/workflows/publish-website.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      # Optional: Setup Pandoc (Quarto bundles Pandoc; keep if you need a specific version)
      #- name: Setup Pandoc
      #  uses: r-lib/actions/setup-pandoc@v2
      #  with:
      #    pandoc-version: '3.1'

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: website

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/_site
          publish_branch: gh-pages
          enable_jekyll: false
